name: Snowlorry
favicon: null
layout_spectrum: 0.19176
typography_spectrum: 0.8141
title: Muso meanderings
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c8dce5'
    - '#ffffff'
    - '#000000'
    - '#778284'
    - '#aca49f'
  brandStrength: 0.12426964822225273
  lightness: 0.6211847844533622
  saturation: 0.7300778974313289
  rhythmicContrast: 0.3694426189176738
purpose: []
